version: '3'
services:
  api:
    user: node
    build: dev.Dockerfile
    restart: always
    working_dir: '/app'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    command: 'nodemon -L bin/www'
    depends_on:
      - mongo
    environment:
      - NODE_ENV:"develop"

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ~/mongo/data:/data/db
